### ISSUE TITLE
IP address 192.168.182.*

### ISSUE THREAD

**Issue by ltedone** [schiavonedimitri/Vodafone-WiFi#5]
Sometimes the IP address is changed to  192.168.182.* instead of 192.168.6.* and the connection doesn't work. Is there any workaround to solve this issue?

**Comment by ltedone** [comment]
Hello,
I am using an Openwrt router and this is my dhcp file. In which section will you add the list server, dnsmasq?

config dnsmasq                                   
        option domainneeded '1'                  
        option boguspriv '1'                     
        option filterwin2k '0'                   
        option localise_queries '1'              
        option rebind_localhost '1'              
        option local '/lan/'                     
        option domain 'lan'                          
        option expandhosts '1'                       
        option nonegcache '0'                        
        option authoritative '1'                     
        option readethers '1'                        
        option leasefile '/tmp/dhcp.leases'          
        option resolvfile '/tmp/resolv.conf.auto'    
        option nonwildcard '1'                       
        option localservice '1'                      
        option rebind_protection '0'                 
                                                     
config dhcp 'lan'                    
        option interface 'lan'                   
        option start '100'                       
        option limit '150'                       
        option leasetime '12h'                   
        option force '1'                         
        option dhcpv6 'disabled'                 
        option ra 'disabled'                         
                                                     
config dhcp 'wan'                                    
        option interface 'wan'                       
        option ignore '1'                            
                                                     
config odhcpd 'odhcpd'                               
        option maindhcp '0'                          
        option leasefile '/tmp/hosts/odhcpd'         
        option leasetrigger '/usr/sbin/odhcpd-update'
        option loglevel '4' 

config dhcp 'guest'                                  
        option interface 'guest'                     
        option start '100'                           
        option leasetime '12h'                       
        option limit '150'                           
        option dhcpv6 'disabled'                     
        option ra 'disabled'                         
                                                     
config domain 'localhost'                                    
        option ip '192.168.8.1'

**Comment by neothematrix** [comment]
@schiavonedimitri  shouldn't the dns exception for custom DNS be:

```
list server '/connectivitycheck.gstatic.com/192.168.6.1'
list server '/connectivitycheck.gstatic.com/192.168.182.1'
```
because the script uses the above url to check connectivity and if you're not logged in, vodafone dns will reply and redirect you to the vodafofone-wifi.com portal (that btw has a public dns record)

@ltedone are you actually using custom dns? you should check /etc/config/network and check if your wan connection has a "list dns" entry if you're not sure.

**Comment by ltedone** [comment]
@neothematrix no, I'm not using custom dns. I will try your suggestion and let you know.
Thanks

**Comment by schiavonedimitri** [comment]
> @schiavonedimitri shouldn't the dns exception for custom DNS be:
> 
> ```
> list server '/it.portal.vodafone-wifi.com/192.168.182.1'
> list server '/it.portal.vodafone-wifi.com/192.168.6.1'
> list server '/connectivitycheck.gstatic.com/192.168.6.1'
> list server '/connectivitycheck.gstatic.com/192.168.182.1'
> ```
> 
> because the script uses the "gstatic.com" url to check connectivity and if you're not logged in, vodafone dns will reply and redirect you to the vodafone-wifi.com portal. So you probably need both dns exceptions.
> 
You are right, i actually do like you pointed because i don't want dns leaks over vodafone dns servers and also because i use dnscrypt-proxy. @ltedone If you don't care about using custom dns servers or having dns leaks to the servers provided by vodafone you can do like i said or else you can  use your own dns and add the exception to be able to authenticate.

**Comment by neothematrix** [comment]
ciao @ltedone,
if you are not using custom dns I'm afraid our suggestions won't make any difference (but I guess it won't hurt trying).
I'd like to understand better your issue, how are you using the script? Is it installed inside a device running openwrt? how do you notice that the ip changes to 192.168.182.x? is it something that happens while you're connected?
Another thing to check is if you have more than one Vodafone-WiFi in range, they all have the same name but they will have a different BSSID, the easiest way to check is by using an app on your phone, for example, "Wifi Analyzer" if you have Android.
I'm saying this because it happened to me (although I didn't notice the different ip range), that I had two Vodafone-WiFi in range, one was working properly, the other one wouldn't even take me to the login page and sometimes my laptop would switch automatically to the non-working one.

**Comment by schiavonedimitri** [comment]
> ciao @ltedone, if you are not using custom dns I'm afraid our suggestions won't make any difference (but I guess it won't hurt trying). I'd like to understand better your issue, how are you using the script? Is it installed inside a device running openwrt? how do you notice that the ip changes to 192.168.182.x? is it something that happens while you're connected? Another thing to check is if you have more than one Vodafone-WiFi in range, they all have the same name but they will have a different BSSID, the easiest way to check is by using an app on your phone, for example, "Wifi Analyzer" if you have Android. I'm saying this because it happened to me (although I didn't notice the different ip range), that I had two Vodafone-WiFi in range, one was working properly, the other one wouldn't even take me to the login page and sometimes my laptop would switch automatically to the non-working one.

For the multi BSSID problem i would suggest to use the package travelmate and either lock to some specific BSSID or order them based on priority. @neothematrix I guess he's issue is that some Vodafone stations give guests dhcp leases in the range 192.168.6.x and others in the 192.168.182.x...but if he never had problems before (meaning he didn't mess with the dns settings so he should've got them from the wan) there should be another issues.

**Comment by neothematrix** [comment]
@schiavonedimitri I solved the multi BSSID just by telling openwrt to connect to a specific BSSID instead of just the WiFi name (option bssid aa:bb:cc:dd....), but of course it depends on the scenario you have, I don't need to move the device and connect to other Vodafone-WiFi so it's ok for me to stick a fixed BSSID.
As per the ip range I've never noticed different ranges, maybe 192.168.182.* ranges are from other vodafone stations and perhaps the login process it's different? it's hard to tell without additional info :-)

**Comment by schiavonedimitri** [comment]
@neothematrix Yes we need more info, although it could be that he authenticates with a specific BSSID and then roams to another one.
@ltedone Could you elaborate on what happens when you run the script on openwrt and provide any logs?

**Comment by ltedone** [comment]
> > @schiavonedimitri shouldn't the dns exception for custom DNS be:
> > ```
> > list server '/it.portal.vodafone-wifi.com/192.168.182.1'
> > list server '/it.portal.vodafone-wifi.com/192.168.6.1'
> > list server '/connectivitycheck.gstatic.com/192.168.6.1'
> > list server '/connectivitycheck.gstatic.com/192.168.182.1'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > because the script uses the "gstatic.com" url to check connectivity and if you're not logged in, vodafone dns will reply and redirect you to the vodafone-wifi.com portal. So you probably need both dns exceptions.
> 
> You are right, i actually do like you pointed because i don't want dns leaks over vodafone dns servers and also because i use dnscrypt-proxy. @ltedone If you don't care about using custom dns servers or having dns leaks to the servers provided by vodafone you can do like i said or else you can use your own dns and add the exception to be able to authenticate.

I added the lines above as you told, but nothing changed. I would like to use custom DNS because I don't like the Vodafone one and I would prefer to have a better privacy, however if I set them on my router they don't work (I think it's a matter of configuration).


> @neothematrix Yes we need more info, although it could be that he authenticates with a specific BSSID and then roams to another one. @ltedone Could you elaborate on what happens when you run the script on openwrt and provide any logs?

I run the script from an OpenWRT router and I am in range of a Vodafone router that broadcasts with the same BSSID on the 2.4 GHz and 5 GHz bands (they are shown as separated from my interface). Usually the 2.4 has IP 192.168.6.x, while the 5 has 192.168.182.x. About one time a day, both network disapper and when they appear again (maybe a reboot?) the IPs are exchanged and usually the 5 GHz disappers, so I can only connect to the 2.4 with IP 192.168.182.x that doesn't work very well.
But if I'm under 192.168.182.x and I open a VPN from my mobile device, everything works fine.
This is what I have know in my /etc/config/dhcp dnsmasq section and below you can see what's shown from the interface

config dnsmasq
    option domainneeded '1'
    option boguspriv '1'
    option filterwin2k '0'
    option localise_queries '1'
    option rebind_localhost '1'
    option local '/lan/'
    option domain 'lan'
    option expandhosts '1'
    option nonegcache '0'
    option authoritative '1'
    option readethers '1'
    option leasefile '/tmp/dhcp.leases'
    option resolvfile '/tmp/resolv.conf.auto'
    option nonwildcard '1'
    option localservice '1'
    option rebind_protection '0'
    list server '/it.portal.vodafone-wifi.com/192.168.182.1'
    list server '/it.portal.vodafone-wifi.com/192.168.6.1'
    list server '/connectivitycheck.gstatic.com/192.168.6.1'
    list server '/connectivitycheck.gstatic.com/192.168.182.1'

![immagine](https://user-images.githubusercontent.com/715588/140640614-8e6bb5c2-5a0a-45e7-b877-d5548acd812d.png)

**Comment by schiavonedimitri** [comment]
Like @neothematrix said try to lock to a specific BSSID, go to wireless settings and add the option lock to BSSID to the 5Ghz network. Then please check your wan settings (interface->wan->advanced settings, do you have enabled the option to "use dns servers advertised by peer". Then show a log of the script if it fails.

**Comment by ltedone** [comment]
> Like @neothematrix said try to lock to a specific BSSID, go to wireless settings and add the option lock to BSSID to the 5Ghz network. Then please check your wan settings (interface->wan->advanced settings, do you have enabled the option to "use dns servers advertised by peer". Then show a log of the script if it fails.

"Use DNS servers advertised by peer" is already checked, I would try by locking the BSSID

**Comment by neothematrix** [comment]
@ltedone I think we're making a lot of confusion here :-D let's stop and restart.

From your screenshot I guess you're running a GL-AR507S am I right? That interface is not the stock OpenWRT so the instructions are slightly different.

But I think we should focus on the 192.168.182.* issue and I'm pretty sure now that it's totally unrelated to DNS, so lets focus on one problem, revert your "list server" and manual dns configuration and stick to the default ones for now, you can play with the custom dns once this issue has been sorted out.

It would be very useful if you did two things:

1) as soon as you see that your connection stops working, go to your GL router and run "logread > /tmp/log.txt" then save that /tmp/log.txt file and post it somewhere (although be aware there could be sensitive information there, like mac addresses you may want to anonymize), the logfile should help understand what's going on.

2) what happens if you run the vodafone.sh script manually when your connection stops working? what's the output? 

Anyway, I think locking the BSSID will probably solve all your issues and probably the script itself is working as intended.

p.s. if you want you (both) can also add me on telegram @gabriele_eleirbag we can exchange a few comments on this :)

**Comment by ltedone** [comment]
@schiavonedimitri @neothematrix thanks for all your support, I solved the issue. It was not related to the script, but it was due to some misconfigurations on my side.
Many thanks again, I close this.
